middlewares: &middlewares
  filter: ''
  rate-limit:
    enabled: false
    frequency: 1
    bucket: 1

account:
  encrypt: false
  status: 2
  relogin:
    disabled: false
    delay: 3
    interval: 0
    max-times: 0
  use-sso-address: true

heartbeat:
  disabled: false
  interval: 5

message:
  post-format: string
  ignore-invalid-cqcode: true
  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false

output:
  # 日志等级 trace, debug, info, warn, error
  log-level: warn
  # 是否启用 DEBUG
  debug: false

servers:
  - ws:
      disabled: false
      middlewares: *middlewares

database:
  leveldb:
    enable: true
